server:
  port: 2023

spring:

  datasource:
    url: jdbc:h2:mem:mintyn
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

payment:
  types:
    - card

device:
  types:
    - mobile
    - web
